name: Build and push pypi package
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          architecture: 'x64'
      - name: Show environment info
        run: make ver info env
      - name: Build package
        run: make pypi-build
      - name: Push package
        run: make pypi-push

